skips:
  - B101 # Use of assert detected.
  - B603 # subprocess call - check for execution of untrusted input
  - B607 # Starting a process with a partial executable path
  - B108 # Probable insecure usage of temp file/directory.
