inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - utils:unsafe
  - duplicated

ignore-paths:
  - c2cciutils/configuration.py

bandit:
  disable:
    - B113 # Call to requests without timeout (didn't work)
