inherits:
  - duplicated
strictness: veryhigh
max-line-length: 110
doc-warnings: true

ignore-paths:
  - c2cciutils/configuration.py

pylint:
  disable:
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - too-many-nested-blocks
    - too-many-lines
    - too-few-public-methods
    - line-too-long # done by Black
    - missing-module-docstring

pycodestyle:
  options:
    max-line-length: 110
  disable:
    - W293 # blank line contains whitespace
    - E501 # line too long, Done by Black

pydocstyle:
  disable:
    - D105 # Missing docstring in magic method
    - D200 # One-line docstring should fit on one line with quotes
    - D202 # No blank lines allowed after function docstring
    - D203 # 1 blank line required before class
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section
mypy:
  run: true

bandit:
  run: true
  options:
    config: .bandit.yaml

# Not working withy current Pyroma version
pyroma:
  run: true

mccabe:
  run: false
