inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - duplicated

doc-warnings: true

ignore-paths:
  - c2cciutils/configuration.py

pylint:
  disable:
    - missing-module-docstring

bandit:
  options:
    config: .bandit.yaml
