inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - duplicated

ignore-paths:
  - c2cciutils/configuration.py

mypy:
  options:
    python-version: '3.9'

bandit:
  disable:
    - B113 # Call to requests without timeout (didn't work)

ruff:
  options:
    target-version: py39
