inherits:
  - utils:base
  - utils:no-design-checks
  - duplicated

mypy:
  options:
    python-version: '3.10'
    ignore-missing-imports: true
    warn:
      - redundant-casts
      - unused-ignores
    check:
      - untyped-defs

bandit:
  options:
    config: .bandit.yaml
ruff:
  options:
    target-version: py310
