#!/usr/bin/env python3

import datetime
import os
from distutils.version import LooseVersion

import requests


def main() -> None:
    url = "https://pypi.org/pypi/c2cciutils/json"
    data = requests.get(url, timeout=30).json()
    versions = [LooseVersion(v) for v in data["releases"].keys()]
    versions = [v for v in versions if len(v.version) == 4]
    versions = sorted(versions)
    version = versions[-1].vstring

    date_str = version.split(".dev")[1][:8]
    date_obj = datetime.datetime.strptime(date_str, "%Y%m%d")
    days = (datetime.datetime.now() - date_obj).days
    required = "true" if days > 30 else "false"

    print(f"days: {days}")
    print(f"required: {required}")
    with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as output_file:
        output_file.write(f"days={days}\n")
        output_file.write(f"required={required}\n")


if __name__ == "__main__":
    main()
