# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema-applications.json

k3d-io/k3d:
  get-file-name: k3d-linux-amd64
  to-file-name: k3d
  finish-commands:
    - - chmod
      - +x
      - k3d
    - - k3d
      - --version
helm/chart-releaser:
  get-file-name: chart-releaser_{short_version}_linux_amd64.tar.gz
  type: tar
  tar-file-name: cr
  to-file-name: cr
  finish-commands:
    - - chmod
      - +x
      - cr
    - - cr
      - version
