name: Auto reviews updates

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  auto-merge:
    name: Auto reviews updates
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/github-script@v6
        with:
          script: |-
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
            })
        if: github.event.pull_request.user.login == 'renovate[bot]'
      - uses: actions/github-script@v6
        with:
          script: |-
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
            });
            github.graphql(`
              mutation {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: "${context.payload.pull_request.node_id}",
                  mergeMethod: SQUASH,
                }) {
                  pullRequest {
                    autoMergeRequest {
                      enabledAt
                    }
                  }
                }
              }
            `)
        if: github.event.pull_request.user.login == 'c2c-bot-gis-ci' and startsWith(github.head_ref, 'dpkg-update/')
